apiVersion: cloudstack.playtika.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: cloudstack-credentials
      namespace: crossplane-system
      key: credentials
