apiVersion: cloudstack.playtika.com/v1alpha1
kind: IPAddress
metadata:
  annotations:
    meta.upbound.io/example-id: cloudstack/v1alpha1/ipaddress
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
