apiVersion: cloudstack.playtika.com/v1alpha1
kind: NetworkACLRule
metadata:
  annotations:
    meta.upbound.io/example-id: cloudstack/v1alpha1/networkaclrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    aclIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    rule:
    - action: allow
      cidrList:
      - 10.0.0.0/8
      ports:
      - "80"
      - 1000-2000
      protocol: tcp
      trafficType: ingress
