apiVersion: cloudstack.playtika.com/v1alpha1
kind: PortForward
metadata:
  annotations:
    meta.upbound.io/example-id: cloudstack/v1alpha1/portforward
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    forward:
    - privatePort: 80
      protocol: tcp
      publicPort: 8080
      virtualMachineId: f8141e2f-4e7e-4c63-9362-986c908b7ea7
    ipAddressIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
