apiVersion: cloudstack.playtika.com/v1alpha1
kind: SSHKeypair
metadata:
  annotations:
    meta.upbound.io/example-id: cloudstack/v1alpha1/sshkeypair
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: myKey
    project: myProject
    publicKey: ${file("~/.ssh/id_rsa.pub")}
