apiVersion: cloudstack.playtika.com/v1alpha1
kind: VPNCustomerGateway
metadata:
  annotations:
    meta.upbound.io/example-id: cloudstack/v1alpha1/vpncustomergateway
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidr: 10.0.0.0/8
    espPolicy: aes256-sha1;modp1024
    gateway: 192.168.0.1
    ikePolicy: aes256-sha1;modp1024
    ipsecPsk: terraform
    name: test-vpc
