// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AffinityGroupInitParameters struct {

	// The description of the affinity group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the affinity group. Changing this
	// forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name or ID of the project to register this
	// affinity group to. Changing this forces a new resource to be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The affinity group type. Changing this
	// forces a new resource to be created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AffinityGroupObservation struct {

	// The description of the affinity group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The id of the affinity group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the affinity group. Changing this
	// forces a new resource to be created.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name or ID of the project to register this
	// affinity group to. Changing this forces a new resource to be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The affinity group type. Changing this
	// forces a new resource to be created.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AffinityGroupParameters struct {

	// The description of the affinity group.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the affinity group. Changing this
	// forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name or ID of the project to register this
	// affinity group to. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The affinity group type. Changing this
	// forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// AffinityGroupSpec defines the desired state of AffinityGroup
type AffinityGroupSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AffinityGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AffinityGroupInitParameters `json:"initProvider,omitempty"`
}

// AffinityGroupStatus defines the observed state of AffinityGroup.
type AffinityGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AffinityGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AffinityGroup is the Schema for the AffinityGroups API. Creates an affinity group.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudstack}
type AffinityGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   AffinityGroupSpec   `json:"spec"`
	Status AffinityGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AffinityGroupList contains a list of AffinityGroups
type AffinityGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AffinityGroup `json:"items"`
}

// Repository type metadata.
var (
	AffinityGroup_Kind             = "AffinityGroup"
	AffinityGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AffinityGroup_Kind}.String()
	AffinityGroup_KindAPIVersion   = AffinityGroup_Kind + "." + CRDGroupVersion.String()
	AffinityGroup_GroupVersionKind = CRDGroupVersion.WithKind(AffinityGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&AffinityGroup{}, &AffinityGroupList{})
}
