// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NetworkACLRuleInitParameters struct {

	// The network ACL ID for which to create the rules.
	// Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/playtika/provider-cloudstack/apis/cloudstack/v1alpha1.NetworkACL
	ACLID *string `json:"aclId,omitempty" tf:"acl_id,omitempty"`

	// Reference to a NetworkACL in cloudstack to populate aclId.
	// +kubebuilder:validation:Optional
	ACLIDRef *v1.Reference `json:"aclIdRef,omitempty" tf:"-"`

	// Selector for a NetworkACL in cloudstack to populate aclId.
	// +kubebuilder:validation:Optional
	ACLIDSelector *v1.Selector `json:"aclIdSelector,omitempty" tf:"-"`

	// USE WITH CAUTION! If enabled all the firewall rules for
	// this network ACL will be managed by this resource. This means it will delete
	// all firewall rules that are not in your config! (defaults false)
	Managed *bool `json:"managed,omitempty" tf:"managed,omitempty"`

	// Specifies how much rules will be created or deleted
	// concurrently. (defaults 2)
	Parallelism *float64 `json:"parallelism,omitempty" tf:"parallelism,omitempty"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Can be specified multiple times. Each rule block supports
	// fields documented below. If managed = false at least one rule is required!
	Rule []NetworkACLRuleRuleInitParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type NetworkACLRuleObservation struct {

	// The network ACL ID for which to create the rules.
	// Changing this forces a new resource to be created.
	ACLID *string `json:"aclId,omitempty" tf:"acl_id,omitempty"`

	// The ACL ID for which the rules are created.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// USE WITH CAUTION! If enabled all the firewall rules for
	// this network ACL will be managed by this resource. This means it will delete
	// all firewall rules that are not in your config! (defaults false)
	Managed *bool `json:"managed,omitempty" tf:"managed,omitempty"`

	// Specifies how much rules will be created or deleted
	// concurrently. (defaults 2)
	Parallelism *float64 `json:"parallelism,omitempty" tf:"parallelism,omitempty"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Can be specified multiple times. Each rule block supports
	// fields documented below. If managed = false at least one rule is required!
	Rule []NetworkACLRuleRuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`
}

type NetworkACLRuleParameters struct {

	// The network ACL ID for which to create the rules.
	// Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/playtika/provider-cloudstack/apis/cloudstack/v1alpha1.NetworkACL
	// +kubebuilder:validation:Optional
	ACLID *string `json:"aclId,omitempty" tf:"acl_id,omitempty"`

	// Reference to a NetworkACL in cloudstack to populate aclId.
	// +kubebuilder:validation:Optional
	ACLIDRef *v1.Reference `json:"aclIdRef,omitempty" tf:"-"`

	// Selector for a NetworkACL in cloudstack to populate aclId.
	// +kubebuilder:validation:Optional
	ACLIDSelector *v1.Selector `json:"aclIdSelector,omitempty" tf:"-"`

	// USE WITH CAUTION! If enabled all the firewall rules for
	// this network ACL will be managed by this resource. This means it will delete
	// all firewall rules that are not in your config! (defaults false)
	// +kubebuilder:validation:Optional
	Managed *bool `json:"managed,omitempty" tf:"managed,omitempty"`

	// Specifies how much rules will be created or deleted
	// concurrently. (defaults 2)
	// +kubebuilder:validation:Optional
	Parallelism *float64 `json:"parallelism,omitempty" tf:"parallelism,omitempty"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Can be specified multiple times. Each rule block supports
	// fields documented below. If managed = false at least one rule is required!
	// +kubebuilder:validation:Optional
	Rule []NetworkACLRuleRuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type NetworkACLRuleRuleInitParameters struct {

	// The action for the rule. Valid options are: allow and
	// deny (defaults allow).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A CIDR list to allow access to the given ports.
	// +listType=set
	CidrList []*string `json:"cidrList,omitempty" tf:"cidr_list,omitempty"`

	// The ICMP code to allow, or -1 to allow any. This
	// can only be specified if the protocol is ICMP. (defaults 0)
	IcmpCode *float64 `json:"icmpCode,omitempty" tf:"icmp_code,omitempty"`

	// The ICMP type to allow, or -1 to allow any. This
	// can only be specified if the protocol is ICMP. (defaults 0)
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// List of ports and/or port ranges to allow. This can only
	// be specified if the protocol is TCP, UDP, ALL or a valid protocol number.
	// +listType=set
	Ports []*string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The name of the protocol to allow. Valid options are:
	// tcp, udp, icmp, all or a valid protocol number.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The traffic type for the rule. Valid options are:
	// ingress or egress (defaults ingress).
	TrafficType *string `json:"trafficType,omitempty" tf:"traffic_type,omitempty"`
}

type NetworkACLRuleRuleObservation struct {

	// The action for the rule. Valid options are: allow and
	// deny (defaults allow).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A CIDR list to allow access to the given ports.
	// +listType=set
	CidrList []*string `json:"cidrList,omitempty" tf:"cidr_list,omitempty"`

	// The ICMP code to allow, or -1 to allow any. This
	// can only be specified if the protocol is ICMP. (defaults 0)
	IcmpCode *float64 `json:"icmpCode,omitempty" tf:"icmp_code,omitempty"`

	// The ICMP type to allow, or -1 to allow any. This
	// can only be specified if the protocol is ICMP. (defaults 0)
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// List of ports and/or port ranges to allow. This can only
	// be specified if the protocol is TCP, UDP, ALL or a valid protocol number.
	// +listType=set
	Ports []*string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The name of the protocol to allow. Valid options are:
	// tcp, udp, icmp, all or a valid protocol number.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The traffic type for the rule. Valid options are:
	// ingress or egress (defaults ingress).
	TrafficType *string `json:"trafficType,omitempty" tf:"traffic_type,omitempty"`

	// +mapType=granular
	Uuids map[string]*string `json:"uuids,omitempty" tf:"uuids,omitempty"`
}

type NetworkACLRuleRuleParameters struct {

	// The action for the rule. Valid options are: allow and
	// deny (defaults allow).
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A CIDR list to allow access to the given ports.
	// +kubebuilder:validation:Optional
	// +listType=set
	CidrList []*string `json:"cidrList" tf:"cidr_list,omitempty"`

	// The ICMP code to allow, or -1 to allow any. This
	// can only be specified if the protocol is ICMP. (defaults 0)
	// +kubebuilder:validation:Optional
	IcmpCode *float64 `json:"icmpCode,omitempty" tf:"icmp_code,omitempty"`

	// The ICMP type to allow, or -1 to allow any. This
	// can only be specified if the protocol is ICMP. (defaults 0)
	// +kubebuilder:validation:Optional
	IcmpType *float64 `json:"icmpType,omitempty" tf:"icmp_type,omitempty"`

	// List of ports and/or port ranges to allow. This can only
	// be specified if the protocol is TCP, UDP, ALL or a valid protocol number.
	// +kubebuilder:validation:Optional
	// +listType=set
	Ports []*string `json:"ports,omitempty" tf:"ports,omitempty"`

	// The name of the protocol to allow. Valid options are:
	// tcp, udp, icmp, all or a valid protocol number.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`

	// The traffic type for the rule. Valid options are:
	// ingress or egress (defaults ingress).
	// +kubebuilder:validation:Optional
	TrafficType *string `json:"trafficType,omitempty" tf:"traffic_type,omitempty"`
}

// NetworkACLRuleSpec defines the desired state of NetworkACLRule
type NetworkACLRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkACLRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkACLRuleInitParameters `json:"initProvider,omitempty"`
}

// NetworkACLRuleStatus defines the observed state of NetworkACLRule.
type NetworkACLRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkACLRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NetworkACLRule is the Schema for the NetworkACLRules API. Creates network ACL rules for a given network ACL.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudstack}
type NetworkACLRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkACLRuleSpec   `json:"spec"`
	Status            NetworkACLRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkACLRuleList contains a list of NetworkACLRules
type NetworkACLRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkACLRule `json:"items"`
}

// Repository type metadata.
var (
	NetworkACLRule_Kind             = "NetworkACLRule"
	NetworkACLRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkACLRule_Kind}.String()
	NetworkACLRule_KindAPIVersion   = NetworkACLRule_Kind + "." + CRDGroupVersion.String()
	NetworkACLRule_GroupVersionKind = CRDGroupVersion.WithKind(NetworkACLRule_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkACLRule{}, &NetworkACLRuleList{})
}
