// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type StaticNATInitParameters struct {

	// The public IP address ID for which static
	// NAT will be enabled. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/playtika/provider-cloudstack/apis/cloudstack/v1alpha1.IPAddress
	IPAddressID *string `json:"ipAddressId,omitempty" tf:"ip_address_id,omitempty"`

	// Reference to a IPAddress in cloudstack to populate ipAddressId.
	// +kubebuilder:validation:Optional
	IPAddressIDRef *v1.Reference `json:"ipAddressIdRef,omitempty" tf:"-"`

	// Selector for a IPAddress in cloudstack to populate ipAddressId.
	// +kubebuilder:validation:Optional
	IPAddressIDSelector *v1.Selector `json:"ipAddressIdSelector,omitempty" tf:"-"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The virtual machine IP address to forward the
	// static NAT traffic to (useful when the virtual machine has secondary
	// NICs or IP addresses). Changing this forces a new resource to be created.
	VMGuestIP *string `json:"vmGuestIp,omitempty" tf:"vm_guest_ip,omitempty"`

	// The virtual machine ID to enable the
	// static NAT feature for. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/playtika/provider-cloudstack/apis/cloudstack/v1alpha1.Instance
	VirtualMachineID *string `json:"virtualMachineId,omitempty" tf:"virtual_machine_id,omitempty"`

	// Reference to a Instance in cloudstack to populate virtualMachineId.
	// +kubebuilder:validation:Optional
	VirtualMachineIDRef *v1.Reference `json:"virtualMachineIdRef,omitempty" tf:"-"`

	// Selector for a Instance in cloudstack to populate virtualMachineId.
	// +kubebuilder:validation:Optional
	VirtualMachineIDSelector *v1.Selector `json:"virtualMachineIdSelector,omitempty" tf:"-"`
}

type StaticNATObservation struct {

	// The static nat ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The public IP address ID for which static
	// NAT will be enabled. Changing this forces a new resource to be created.
	IPAddressID *string `json:"ipAddressId,omitempty" tf:"ip_address_id,omitempty"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The virtual machine IP address to forward the
	// static NAT traffic to (useful when the virtual machine has secondary
	// NICs or IP addresses). Changing this forces a new resource to be created.
	VMGuestIP *string `json:"vmGuestIp,omitempty" tf:"vm_guest_ip,omitempty"`

	// The virtual machine ID to enable the
	// static NAT feature for. Changing this forces a new resource to be created.
	VirtualMachineID *string `json:"virtualMachineId,omitempty" tf:"virtual_machine_id,omitempty"`
}

type StaticNATParameters struct {

	// The public IP address ID for which static
	// NAT will be enabled. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/playtika/provider-cloudstack/apis/cloudstack/v1alpha1.IPAddress
	// +kubebuilder:validation:Optional
	IPAddressID *string `json:"ipAddressId,omitempty" tf:"ip_address_id,omitempty"`

	// Reference to a IPAddress in cloudstack to populate ipAddressId.
	// +kubebuilder:validation:Optional
	IPAddressIDRef *v1.Reference `json:"ipAddressIdRef,omitempty" tf:"-"`

	// Selector for a IPAddress in cloudstack to populate ipAddressId.
	// +kubebuilder:validation:Optional
	IPAddressIDSelector *v1.Selector `json:"ipAddressIdSelector,omitempty" tf:"-"`

	// The name or ID of the project to deploy this
	// instance to. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// The virtual machine IP address to forward the
	// static NAT traffic to (useful when the virtual machine has secondary
	// NICs or IP addresses). Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	VMGuestIP *string `json:"vmGuestIp,omitempty" tf:"vm_guest_ip,omitempty"`

	// The virtual machine ID to enable the
	// static NAT feature for. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=github.com/playtika/provider-cloudstack/apis/cloudstack/v1alpha1.Instance
	// +kubebuilder:validation:Optional
	VirtualMachineID *string `json:"virtualMachineId,omitempty" tf:"virtual_machine_id,omitempty"`

	// Reference to a Instance in cloudstack to populate virtualMachineId.
	// +kubebuilder:validation:Optional
	VirtualMachineIDRef *v1.Reference `json:"virtualMachineIdRef,omitempty" tf:"-"`

	// Selector for a Instance in cloudstack to populate virtualMachineId.
	// +kubebuilder:validation:Optional
	VirtualMachineIDSelector *v1.Selector `json:"virtualMachineIdSelector,omitempty" tf:"-"`
}

// StaticNATSpec defines the desired state of StaticNAT
type StaticNATSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     StaticNATParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StaticNATInitParameters `json:"initProvider,omitempty"`
}

// StaticNATStatus defines the observed state of StaticNAT.
type StaticNATStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StaticNATObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StaticNAT is the Schema for the StaticNATs API. Enables static NAT for a given IP address.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudstack}
type StaticNAT struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              StaticNATSpec   `json:"spec"`
	Status            StaticNATStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StaticNATList contains a list of StaticNATs
type StaticNATList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StaticNAT `json:"items"`
}

// Repository type metadata.
var (
	StaticNAT_Kind             = "StaticNAT"
	StaticNAT_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StaticNAT_Kind}.String()
	StaticNAT_KindAPIVersion   = StaticNAT_Kind + "." + CRDGroupVersion.String()
	StaticNAT_GroupVersionKind = CRDGroupVersion.WithKind(StaticNAT_Kind)
)

func init() {
	SchemeBuilder.Register(&StaticNAT{}, &StaticNATList{})
}
